# Generated by Django 6.1 on 2026-09-07 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
