# Generated by Django 6.1 on 2026-08-29 22:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bank', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.CharField(choices=[('in_progress', 'Inprogress'), ('finished', 'Finishied')], default='in_progress', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'game_session',
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('manual_adjustment', models.IntegerField(default=0)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.session')),
            ],
            options={
                'db_table': 'game_player',
            },
        ),
        migrations.CreateModel(
            name='SessionQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('state', models.CharField(choices=[('locked', 'Locked'), ('opened', 'Opened'), ('judged', 'Judged')], default='locked', max_length=10)),
                ('opened_at', models.DateTimeField(blank=True, null=True)),
                ('judged_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_player', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assigned_questions', to='game.player')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bank.question')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.session')),
                ('winner_player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='won_questions', to='game.player')),
            ],
            options={
                'db_table': 'game_sessionquestion',
            },
        ),
        migrations.CreateModel(
            name='SessionTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.session')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bank.topic')),
            ],
            options={
                'db_table': 'game_sessiontopic',
            },
        ),
        migrations.AddConstraint(
            model_name='session',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'in_progress')), fields=('host',), name='one_active_session_per_host'),
        ),
        migrations.AddConstraint(
            model_name='sessionquestion',
            constraint=models.UniqueConstraint(fields=('session', 'question', 'assigned_player'), name='question_unique_per_session_and_player'),
        ),
        migrations.AddConstraint(
            model_name='sessiontopic',
            constraint=models.UniqueConstraint(fields=('session', 'topic'), name='cant_pick_same_topic_in_same_session'),
        ),
    ]
