# Generated by Django 6.1 on 2026-08-30 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='status',
            field=models.CharField(choices=[('in_progress', 'Inprogress'), ('finished', 'Finished')], default='in_progress', max_length=15),
        ),
    ]
